language: node_js
sudo: false
node_js:
  - "4.2.4"
script:
  - echo "Testing..."
  - gulp travis-tests
install:
  - npm install -g firebase-tools
  - npm install
after_success:
  - echo "Building..."
  - gulp build
  - echo "Deploying..."
  - firebase deploy --token ${FIREBASE_TOKEN} -f ${FIREBASE_ENV}
  - echo "Done"
cache:
    directories:
      - node_modules
branches:
    only:
      - master