export const A = "A"
export const B = "B"
export const C = "C"

export const STICK = "黏邊位 (Stick)"
export const CLIP = "夾位 (Clip)"
export const TOUNGUE = "脷仔 (Toungue)"
export const TEAR = "撕邊位 (Tear)"
export const BACK = "扣背 (Back)"
export const OTHER = "其他 (Other)"
export const DIAMETER = "直徑 (Diameter)"
export const HEIGHT = "高 (Height)"
export const LIDLENGTH = "蓋長度"
export const ROLL = "卷邊 (roll)"

export const VERTICAL = "通道 (Vertical)"
export const HORIZONTAL = "橫 (Horizontal)"
export const AMOUNT = "數量"
export const BODY = "筒身 (Body)"
export const BASE = "蓋片 (Base)"
export const LID = "桶蓋 (Lid)"